// nuxt-app/pages/admin.vue
<script setup lang="ts">
useHead({
  title: 'Admin Panel - Pokemon Manager'
});
</script>

<template>
  <div>
    <!--
      NUXT ADVANTAGE: Full Hydration with Shared State

      Unlike Astro's islands architecture, Nuxt hydrates the entire page.
      This means:
      - All components can share state through Vue's reactivity
      - Can use Pinia, composables, or provide/inject for global state
      - No need to bundle everything into a single "island" component
      - Components can communicate freely through events or shared state

      Trade-off: More JavaScript is sent to the client, but complex
      admin UIs work naturally without architectural constraints.

      For this demo, we use a single AdminPanel component to match
      the Astro implementation, but in a real Nuxt app you could
      split this into multiple components that share state via
      Pinia or composables.
    -->
    <AdminPanel />
  </div>
</template>

<style scoped>
div {
  min-height: 100vh;
  background: #f5f5f5;
}
</style>

// nextjs-app/app/admin/page.tsx
import { Metadata } from 'next';
import AdminPanel from './AdminPanel';

export const metadata: Metadata = {
  title: 'Admin Panel - Pokemon Manager',
};

/*
  NEXT.JS ARCHITECTURE: React Server Components + Client Components

  This page demonstrates Next.js's hybrid approach:
  - The page wrapper is a Server Component (no JavaScript shipped)
  - AdminPanel is a Client Component ('use client') for interactivity

  Comparison with Astro Islands:
  - Similar concept: Server-rendered shell with hydrated "islands"
  - Key difference: All client components share React's runtime
  - In Astro: Each island is isolated, cannot share state
  - In Next.js: Client components can share state via context/stores

  Trade-off:
  - More flexible state sharing than Astro
  - But still ships React runtime (~134 KB) even for simple pages
  - Astro ships 0 KB JS for static pages

  For complex admin UIs like this, Next.js works naturally because
  all interactive parts share the React runtime and can communicate.
*/

export default function AdminPage() {
  return (
    <div style={{ minHeight: '100vh', background: '#f5f5f5' }}>
      <AdminPanel />
    </div>
  );
}
